# This file was auto-generated by the framework. You can add data models or change the existing ones

from moose_lib import ClickhouseEngines, OlapTable, Stream, UInt8, IngestApi, IngestConfig, DeadLetterQueue, Key
from datetime import datetime
from typing import Optional
from pydantic import BaseModel



class Foo(BaseModel):
    primary_key: Key[str]
    timestamp: float
    optional_text: Optional[str]
    myNumberField: int

class Bar(BaseModel):
    primary_key: Key[str]
    utc_timestamp: datetime
    has_text: bool
    text_length: int

foo_table = OlapTable[Foo]("Foo", {
    "engine": ClickhouseEngines.ReplacingMergeTree,
    "order_by_fields": ("myNumberField",),
})

bar_table = OlapTable[Bar]("Bar", {
    "engine": ClickhouseEngines.ReplacingMergeTree,
    "order_by_fields": ("text_length",),
})

foo_stream = Stream[Foo]("Foo", {
    "destination": foo_table,
})

dead_letter_queue = DeadLetterQueue[Foo]("Foo", {})

foo_api = IngestApi[Foo]("Foo", {
    "destination": foo_stream,
    "dead_letter_queue": foo_stream.default_dead_letter_queue,
})

bar_stream = Stream[Bar]("Bar", {
    "destination": bar_table,
})

bar_api = IngestApi[Bar]("Bar", {
    "destination": bar_stream,
    "dead_letter_queue": bar_stream.default_dead_letter_queue,
})
